# Generated by Django 5.0.3 on 2026-05-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_code', models.CharField(max_length=30)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'qr_verification_logs',
                'ordering': ['-verified_at'],
            },
        ),
    ]
