# Generated by Django 5.0.3 on 2026-05-20 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cert_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('roll_no', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('cert_type', models.CharField(choices=[('degree', 'Degree Certificate'), ('experience', 'Experience Certificate'), ('completion', 'Completion Certificate'), ('relieving', 'Relieving Certificate')], max_length=20)),
                ('mode', models.CharField(choices=[('college', 'College'), ('company', 'Company')], default='college', max_length=10)),
                ('department', models.CharField(max_length=200)),
                ('course', models.CharField(blank=True, max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('cgpa', models.CharField(blank=True, max_length=10)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cert_type', models.CharField(choices=[('degree', 'Degree Certificate'), ('experience', 'Experience Certificate'), ('completion', 'Completion Certificate'), ('relieving', 'Relieving Certificate')], max_length=20)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='templates/')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'certificate_templates',
            },
        ),
    ]
